config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "people#index"
  resources :people
  resources :detail
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
  #Association
  belongs_to :person

  #validation
  validates :email, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  #Association
  has_one :detail, dependent: :destroy
  accepts_nested_attributes_for :detail, allow_destroy: true

  #validation
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    def index
      @people = Person.all
      @person = Person.new
    end

    def show
      @person = Person.find(params[:id])
    end
  
    def create
      @person = Person.new(person_params)
      if @person.save
        @person.create_detail(detail_params) unless @person.detail.present?
        redirect_to people_url, notice: "Person was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
    
    private

    def person_params
      params.require(:person).permit(:name, detail_attributes: [:id, :title, :email, :age, :phone, :_destroy])
    end

    def detail_params
      params[:person][:details].permit(:title, :age, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketcircle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: @person, local: true, class:"text-lg inline-block my-3 w-72") do |form| %>
  <div class="mb-5">
    <%= form.label :name, "Name" %><br>
    <%= form.text_field :name, placeholder: "Enter Name", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>

    <%= form.fields_for :details do |detail_form| %>
      <%= detail_form.label :email %><br>
      <%= detail_form.email_field :email, placeholder: "Enter Email", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>

      <%= detail_form.label :age %><br>
      <%= detail_form.number_field :age, placeholder: "Enter Age", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>

      <%= detail_form.label :title %><br>
      <%= detail_form.text_field :title, placeholder: "Enter Title", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>

      <%= detail_form.label :phone %><br>
      <%= detail_form.telephone_field :phone, placeholder: "Enter Phone Number", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
    <% end %>

    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/people/_person.html.erb
<turbo-frame id="<%= dom_id person %>" class="block">
<div class="block">
  <%= person.name %>
  <%= link_to "Show", person_path(person),
              class: "btn bg-gray-100"%>

</div>
  
</turbo-frame>

app/views/people/index.html.erb
<div>
  <h1 class="font-bold text-2xl">Create New Person</h1>
  <div class="mt-4">
    <%= render "form", person: @person %>
  </div>
</div>
<div>
  <h1 class="font-bold text-lg mb-7">People</h1>
  <div class="px-5" data-controller="people">
    <%= render @people %>
  </div>
</div>


<%= turbo_stream_from 'people' do %><% end %>

app/views/people/show.html.erb
<div>
  <turbo-frame id="<%= dom_id @person %>">
    <dl>
      <dt>Name: <%= @person.name %></dt>
      <% if @person.detail %>
        <dt>Email: <%= @person.detail.email %></dt>
        <dt>Age: <%= @person.detail.age %></dt>
        <dt>Title: <%= @person.detail.title %></dt>
        <dt>Phone: <%= @person.detail.phone %></dt>
      <% end %>
    </dl> 

    <%= link_to "Back", people_path, class: "btn bg-red-100" %>
  </turbo-frame>
</div>